Cargo remove proc-macro=true
proc-macro causes failure during `cargo test`

    error: the linked panic runtime `panic_unwind` is not compiled with this crate's panic strategy `abort`